project:
  type: website
  output-dir: ../

website:
  title: "বিশ্ব ডট কম"
  favicon: assets/bishwo_clean.png
  body-footer: |
    [বিশ্ব ডট কম](https:www.bishwo.com) | সম্পাদক: [আব্দুল্যাহ আদিল মাহমুদ](https://www.thinkermahmud.com/)
  site-url: "https://portal.statmania.info/"
  google-analytics:
    tracking-id: "G-BEELJ2ZRED"
  navbar:
    background: light
    logo: assets/bishwo_clean.png
    logo-alt: "বিশ্ব ডট কম Logo."
    left:
      - href: index.qmd
        text: হোম
      - href: "index.html#category=সৌরজগৎ"
        text: সৌরজগৎ
      - href: "index.html#category=নক্ষত্র"
        text: নক্ষত্র
      - href: "index.html#category=কসমোলজি"
        text: কসমোলজি
      - href: "https://sky.bishwo.com/"
        text: পুরাতন সাইট
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



