project:
  type: website
  output-dir: ../

website:
  title: "বিশ্ব ডট কম"
  favicon: assets/bishwo_clean.png
  page-navigation: true
  page-footer:
    left: |
      Built with [Quarto](https://quarto.org/)
    center: |
      [আর্কাইভ](https://sky.bishwo.com/) | [বিশ্বটিউব](https://www.youtube.com/@Bishwotube)

      [বিশ্ব ডট কম](https://www.bishwo.com) | সম্পাদক: [আব্দুল্যাহ আদিল মাহমুদ](https://www.thinkermahmud.com/)
    right:
      - icon: github
        href: https://github.com/bishwo-web
        aria-label: Quarto GitHub
      - icon: youtube
        href: https://www.youtube.com/@Bishwotube
      - icon: rss
        href: https://www.bishwo.com/index.xml
        aria-label: Quarto Blog RSS
  site-url: "https://www.bishwo.com"
  google-analytics:
    tracking-id: "G-9XSTMB89MF"
  navbar:
    background: light
    logo: assets/bishwo_clean.png
    logo-alt: "বিশ্ব ডট কম Logo."
    left:
      - href: index.qmd
        text: হোম
        icon: house
      - href: "index.html#category=সৌরজগৎ"
        text: সৌরজগৎ
        icon: sun
      - href: "index.html#category=নক্ষত্র"
        text: নক্ষত্র
        icon: stars
      - href: "index.html#category=রাতের আকাশ"
        text: রাতের আকাশ
        icon: moon-stars-fill
      - text: "অন্যান্য"
        icon: "feather"
        menu:
          - text: "ভিডিও"
            icon: camera-video
            href: "https://www.youtube.com/@Bishwotube"
          - text: "কসমোলজি"
            icon: tropical-storm
            href: "index.html#category=কসমোলজি"
          - text: "সাম্প্রতিক"
            icon: card-checklist
            href: latest.qmd
      - href: "https://sky.bishwo.com/"
        text: আর্কাইভ
    right:
      - text: সকল লেখক
        icon: people-fill
        menu:
          - text: "আব্দুল্যাহ আদিল মাহমুদ"
            href: abdullah-adil-mahmud.qmd
            icon: person-circle
          - text: "নাসরুল্লাহ মাসুদ"
            href: nasrullah-masud.qmd
            icon: person-circle
      - text: ভিডিও
        icon: camera-video
        menu:
          - text: "বিশ্বটিউব"
            href: "https://www.youtube.com/@Bishwotube"
            icon: youtube
          - text: "ফিচারড ভিডিও"
            href: videos.qmd
            icon: camera-video-fill

  sidebar:
#    - id: abdullah-adil-mahmud
    collapse-level: 2
    contents: "posts/"
    title: "পোস্টসমূহ"
    style: "docked"
    search: true

format:
  html:
    #theme: flatly
    theme: litera
    css: styles.css
    toc: true



