project:
  type: website
  output-dir: ../

website:
  title: "বিশ্ব ডট কম"
  favicon: assets/bishwo_clean.png
  page-footer:
    left: |
      Built with [Quarto](https://quarto.org/)
    center: |
      [আর্কাইভ](https://sky.bishwo.com/) | [বিশ্বটিউব](https://www.youtube.com/@Bishwotube)

      [বিশ্ব ডট কম](https://www.bishwo.com) | সম্পাদক: [আব্দুল্যাহ আদিল মাহমুদ](https://www.thinkermahmud.com/)
    right:
      - icon: github
        href: https://github.com/bishwo-web
        aria-label: Quarto GitHub
      - icon: rss
        href: https://www.bishwo.com/index.xml
        aria-label: Quarto Blog RSS
  site-url: "https://www.bishwo.com"
  google-analytics:
    tracking-id: "G-9XSTMB89MF"
  navbar:
    background: light
    logo: assets/bishwo_clean.png
    logo-alt: "বিশ্ব ডট কম Logo."
    left:
      - href: index.qmd
        text: হোম
        icon: house
      - href: "index.html#category=সৌরজগৎ"
        text: সৌরজগৎ
        icon: sun
      - href: "index.html#category=নক্ষত্র"
        text: নক্ষত্র
        icon: stars
      - href: "index.html#category=রাতের আকাশ"
        text: রাতের আকাশ
        icon: moon-stars-fill
      - text: "অন্যান্য"
        icon: "feather"
        menu:
          - text: "ভিডিও"
            icon: "camera-video"
            href: "https://www.youtube.com/@Bishwotube"
          - text: "কসমোলজি"
            icon: "tropical-storm"
            href: "index.html#category=কসমোলজি"
      - href: "https://sky.bishwo.com/"
        text: পুরাতন সাইট
    right:
      - about.qmd
      - href: "https://www.youtube.com/@Bishwotube"
        text: বিশ্বটিউব
        icon: "camera-video"

format:
  html:
    #theme: flatly
    theme: litera
    css: styles.css



